function(rhi_symlink_shaders ABSOLUTE_TARGET_SHADER_DIRECTORY)
    if(NOT UNIX)
        file(TO_NATIVE_PATH ${ABSOLUTE_TARGET_SHADER_DIRECTORY}/rhi DST_PATH)
        file(TO_NATIVE_PATH ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/shaders/rhi SRC_PATH)
        if(NOT EXISTS ${DST_PATH})
            message(STATUS "Creating symlink/junction between ${DST_PATH} and ${SRC_PATH}")
            execute_process(COMMAND cmd.exe /c mklink /D /J "${DST_PATH}" "${SRC_PATH}" >NUL)
        endif()
    endif()
endfunction()
